name: melancholy
favicon: null
layout_spectrum: 0.2429
typography_spectrum: 0.6997577380388975
title: melancholy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6666056662797928
  lightness: 0.9086368030402809
  saturation: 0.7889816265087575
  rhythmicContrast: 0.39616259979084134
purpose: []
